modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "adaptedmobs"
version = "1.0.0"
displayName = "Adapted Mobs"
authors = "Cf28"
credits = "Cf28, BlackGear, Auxiliary, EB Mario, Pee Dog, Daveyx0"
description = '''
The Spiritual Successor to Primitive Mobs
'''
logoFile = "icon.png"

[[dependencies.adaptedmobs]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adaptedmobs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"