# Project
group=com.cf28
version=1.1.1
java_version=21

# Mod properties
mod_id=adaptedmobs
archives_name=AdaptedMobs
mod_name=Adapted Mobs
mod_author=Cf28
credits=Cf28, Evanbones, BlackGear, Auxiliary, EB Mario, Pee Dog, Daveyx0
license=MIT
description=The Spiritual Successor to Primitive Mobs!

# Minecraft properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,)
neo_form_version=1.21.1-20240808.144430

# Dependencies
fabric_loader_version=0.19.3
fabric_api_version=0.116.7+1.21.1
neoforge_version=21.1.234
neoforge_loader_version_range=[2,)
parchment_version=2024.11.17
tolerable_creepers_version=2.2.4-1.21.1
emi_version=1.1.22+1.21.1
yacl_version=3.8.0+1.21.1
mod_menu_version=11.0.3

# Gradle
org.gradle.jvmargs=-Xmx2G -XX:+UseG1GC
org.gradle.parallel=true